---
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args:
          - --unsafe
      - id: check-toml
      - id: end-of-file-fixer
        exclude: '(\.svg$|\.md$|\.snap$|\.waldiez$|\.waldiezTool$|\.waldiezModel$|\.waldiezAgent$)'
      - id: trailing-whitespace
        exclude: '(\.svg$|\.md$|\.snap$|\.waldiez$|\.waldiezTool$|\.waldiezModel$|\.waldiezAgent$)'

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.13

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config", .flake8]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "-rn"
          - "-sn"
          - "--rcfile=pyproject.toml"

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args:
          - "--config"
          - "pyproject.toml"

      - id: basedpyright
        name: basedpyright
        entry: python scripts/lint.py
        language: system
        pass_filenames: false
        require_serial: true
        types: [python]
        args:
          - "--pyright"

      - id: header
        name: header
        language: system
        pass_filenames: false
        require_serial: true
        types: [python]
        entry: python scripts/header.py
