---
name: Lint 🧹

# yamllint disable rule:truthy
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
  merge_group:
  workflow_dispatch:

jobs:
  lint:
    name: Run linters
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/AppData/Local/pip/Cache
            ~/Library/Caches/pip
          key: pip-lint-${{ runner.os }}-py${{ matrix.python-version }}-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            pip-lint-${{ runner.os }}-py${{ matrix.python-version }}-
            pip-lint-${{ runner.os }}-

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Cache bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: bun-${{ runner.os }}-${{ hashFiles('package.json', 'bun.lock') }}
          restore-keys: |
            bun-${{ runner.os }}-

      - name: Install ts dependencies
        run: bun install

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/main.txt -r requirements/dev.txt -r requirements/test.txt

      - name: Run Python linters
        run: |
          python scripts/lint.py

      - name: Run TypeScript linters
        run: |
          bun run lint
