---
name: Publish 📦

# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  publish_waldiez_to_npm:
    name: Publish React 🌐 distribution 📦 to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: "recursive"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2.0.2

      - name: Build and publish to NPM
        # publish only on new tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun install
          bun clean
          mkdir -p .local
          mv README.md .local/README.md.bak
          mv README.npm.md README.md
          bun build:lib
          bun publish
          mv README.md README.npm.md 2>/dev/null || true
          mv .local/README.md.bak README.md 2>/dev/null || true

      - name: Dry-run publish to NPM
        if: github.event_name == 'workflow_dispatch'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun install
          bun clean
          bun build:lib
          bun publish --dry-run

  package_waldiez_python:
    runs-on: ubuntu-latest
    name: Package Python 🐍 distribution 📦
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: "recursive"

      - name: Set up Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install --break-system-packages build twine

      - name: Pin optional extras
        run: |
          python scripts/pin_extras.py

      - name: Build 🏗️
        run: |
          mkdir -p dist/python
          python -m build --sdist --wheel --outdir dist/python
          python -m twine check dist/python/*

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4.6.2
        with:
          name: waldiez-python
          path: |
            dist/python

  publish_waldiez_to_pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    needs: package_waldiez_python
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/waldiez
    steps:
      - name: Download the artifact from the python package
        uses: actions/download-artifact@v5.0.0
        with:
          name: waldiez-python
          path: dist/python

      - name: List the distribution packages
        if: github.event_name == 'workflow_dispatch'
        run: |
          ls -la dist/python

      - name: Publish distribution 📦 to PyPI
        # publish only on new tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/python
